In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a dataframe from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating NumPy Arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
ones = np.ones((2,3),dtype = int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
zeros = np.zeros((2,3),dtype = int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[2, 1, 3, 8, 4],
       [3, 6, 8, 3, 6],
       [4, 2, 9, 4, 9]])

In [22]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.70554068, 0.58649047, 0.99942299],
       [0.96377224, 0.21750493, 0.35728238],
       [0.76660174, 0.36373381, 0.05079905],
       [0.60911247, 0.11356049, 0.30170479],
       [0.97237264, 0.2281921 , 0.60518936]])

In [24]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.32094868, 0.59045397, 0.01314037],
       [0.84750075, 0.09577925, 0.68846913],
       [0.79449709, 0.98920892, 0.33544626],
       [0.5531419 , 0.67982049, 0.70794199],
       [0.25821516, 0.83687139, 0.54151832]])

In [34]:
#Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[3, 2, 7],
       [2, 0, 0],
       [4, 5, 5],
       [6, 8, 4],
       [1, 4, 9]])

In [37]:
unique_array = np.unique(random_array_4)
unique_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
unique_array_2 = np.random.randint(10,size=(5,3))
unique_array_2

array([[8, 1, 1],
       [7, 9, 9],
       [3, 6, 7],
       [2, 0, 3],
       [5, 9, 4]])

## Viewing arrays and matrices

In [39]:
a1[0]

1

In [40]:
a2[0]

array([1. , 2. , 3.3])

In [41]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a1[1]

2

In [43]:
a2[1]

array([4. , 5. , 6.5])

In [44]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [45]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [47]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]],


       [[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]]])

In [48]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [49]:
# Get the first 4 numbers of the ineer most arrays
a4[ :, :, :, :4]

array([[[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]],


       [[[8, 8, 2, 3],
         [0, 8, 8, 3],
         [2, 8, 4, 3],
         [4, 3, 6, 9]],

        [[0, 8, 5, 9],
         [9, 6, 5, 3],
         [8, 0, 4, 9],
         [5, 7, 8, 8]],

        [[2, 8, 6, 6],
         [1, 6, 8, 8],
         [2, 3, 6, 3],
         [5, 7, 0, 8]]]])

## Manipulating Arrays

### Arithmetic

In [50]:
a1

array([1, 2, 3])

In [51]:
ones = np.ones(3,dtype = int)
ones

array([1, 1, 1])

In [52]:
a1+=ones
a1

array([2, 3, 4])

In [53]:
a1*a2

array([[ 2. ,  6. , 13.2],
       [ 8. , 15. , 26. ]])

In [55]:
a2.reshape((3,2))

array([[1. , 2. ],
       [3.3, 4. ],
       [5. , 6.5]])

## Aggregation

In [64]:
sum(a1)

9

In [65]:
a1

array([2, 3, 4])

In [66]:
np.sum(a1)

9

In [67]:
np.sum(a3)

171

In [68]:
massive_array = np.random.random(100000)

In [69]:
%timeit sum(massive_array)

8.77 ms ± 78.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [71]:
%timeit np.sum(massive_array)

31.8 µs ± 276 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [72]:
np.mean(a2)

3.6333333333333333

In [73]:
np.max(a3)

18

In [75]:
np.std(a2,axis=1)

array([0.94162979, 1.02740233])

In [76]:
np.var(a3,axis=2)

array([[0.66666667, 0.66666667, 0.66666667],
       [0.66666667, 0.66666667, 0.66666667]])

## Reshaping and Transposing

In [78]:
a2 = a2.reshape((3,2))

In [79]:
a2

array([[1. , 2. ],
       [3.3, 4. ],
       [5. , 6.5]])

In [80]:
a2 = a2.reshape(2,3,1)

In [82]:
a2*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [83]:
a2.T

array([[[1. , 4. ],
        [2. , 5. ],
        [3.3, 6.5]]])

In [84]:
a2

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [85]:
a1

array([2, 3, 4])

In [86]:
a1.T

array([2, 3, 4])

In [87]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [88]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

## Dot Product

In [89]:
np.random.seed(seed=0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [91]:
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [96]:
mat3 = np.dot(mat1.reshape(3,5),mat2)
mat3

array([[ 90, 103,  62],
       [143, 132, 123],
       [197, 148, 151]])

In [94]:
mat4 = np.dot(mat1,mat2.T)
mat4

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot Product Example (Nut Butter Sales)

In [97]:
np.random.seed(0)

In [98]:
days = pd.Series(["Monday","Tuesday","Wednesday","Thursday","Friday"])

In [101]:
nut_butter_sales = pd.DataFrame({" ":days})

In [102]:
nut_butter_sales["Almond butter"] = np.random.randint(10,size=(5,1))

In [103]:
nut_butter_sales

Almond butter
0     Monday              5
1    Tuesday              0
2  Wednesday              3
3   Thursday              3
4     Friday              7

In [105]:
nut_butter_sales.reset_index(drop=True,inplace=True)
nut_butter_sales

index             Almond butter
0      0     Monday              5
1      1    Tuesday              0
2      2  Wednesday              3
3      3   Thursday              3
4      4     Friday              7

In [106]:
nut_butter_sales.drop("index",axis=1,inplace=True)
nut_butter_sales

Almond butter
0     Monday              5
1    Tuesday              0
2  Wednesday              3
3   Thursday              3
4     Friday              7

In [107]:
nut_butter_sales.drop("Almond butter",axis=1,inplace=True)
nut_butter_sales

0     Monday
1    Tuesday
2  Wednesday
3   Thursday
4     Friday

In [108]:
np.random.seed(0)
nut_butter_sales["Almond butter"] = np.random.randint(20,size=(5,1))
nut_butter_sales["Peanut butter"] = np.random.randint(10,size=(5,1))
nut_butter_sales["Cashew butter"] = np.random.randint(10,size=(5,1))
nut_butter_sales

Almond butter  Peanut butter  Cashew butter
0     Monday             12              7              4
1    Tuesday             15              9              7
2  Wednesday              0              3              6
3   Thursday              3              5              8
4     Friday              3              2              8

In [109]:
nut_butter_sales.drop("Peanut butter",axis=1,inplace=True)
nut_butter_sales.drop("Cashew butter",axis=1,inplace=True)
nut_butter_sales

Almond butter
0     Monday             12
1    Tuesday             15
2  Wednesday              0
3   Thursday              3
4     Friday              3

In [111]:
np.random.seed(0)
nut_butter_sales["Almond butter"] = np.random.randint(20,size=(5,1))
nut_butter_sales["Peanut butter"] = np.random.randint(20,size=(5,1))
nut_butter_sales["Cashew butter"] = np.random.randint(20,size=(5,1))
nut_butter_sales

Almond butter  Peanut butter  Cashew butter
0     Monday             12              7              6
1    Tuesday             15              9             12
2  Wednesday              0             19              1
3   Thursday              3             18              6
4     Friday              3              4              7

In [112]:
nut_butter_sales

Almond butter  Peanut butter  Cashew butter
0     Monday             12              7              6
1    Tuesday             15              9             12
2  Wednesday              0             19              1
3   Thursday              3             18              6
4     Friday              3              4              7

In [114]:
np.random.seed(0)
#Number of jars sold
sales_amount = np.random.randint(20,size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [116]:
#Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amount, index=["Mon","Tues","Wed","Thurs","Fri"],columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [118]:
#Create a prices array
prices = np.array([10,8,12])
#Create butter_price DataFrame
butter_price  = pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Almond butter","Peanut butter","Cashew butter"])
butter_price

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [119]:
prices.shape

(3,)

In [120]:
sales_amount.shape

(5, 3)

In [121]:
total_sales = sales_amount.dot(prices)
total_sales

array([240, 138, 458, 232, 142])

In [122]:
weekly_sales["Total $"] = total_sales

In [123]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total $
Mon               12             15              0      240
Tues               3              3              7      138
Wed                9             19             18      458
Thurs              4              6             12      232
Fri                1              6              7      142

In [124]:
total = np.sum(total_sales)
total

1210

In [125]:
butter_price["Total $"] = total
butter_price

Almond butter  Peanut butter  Cashew butter  Total $
Price             10              8             12     1210

In [126]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total $
Mon               12             15              0      240
Tues               3              3              7      138
Wed                9             19             18      458
Thurs              4              6             12      232
Fri                1              6              7      142

In [127]:
butter_price

Almond butter  Peanut butter  Cashew butter  Total $
Price             10              8             12     1210

In [128]:
nut_butter_sales = pd.concat([weekly_sales,butter_price],axis=0)
nut_butter_sales

Almond butter  Peanut butter  Cashew butter  Total $
Mon               12             15              0      240
Tues               3              3              7      138
Wed                9             19             18      458
Thurs              4              6             12      232
Fri                1              6              7      142
Price             10              8             12     1210

In [129]:
nut_butter_sales.to_csv("nut-butter-sales.csv")

In [130]:
nut_butter_sales.to_excel("nut-butter-sales.xlsx")

## Sorting Arrays

In [132]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [133]:
np.sort(random_array) #by default sorting by columns, axis=1

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [135]:
np.sort(random_array,axis=0) #sorting by rows, axis=0

array([[3, 5, 0, 2, 0],
       [7, 8, 1, 3, 3],
       [8, 9, 4, 5, 9]])

## Practical Example - NumPy in Action

![](2002920.jpg)

In [137]:
# Turn an image into a NumPy array
from matplotlib.image import imread

Kroos = imread("2002920.jpg")
Kroos

array([[[ 65,  85,  96],
        [ 61,  81,  92],
        [ 57,  77,  88],
        ...,
        [ 85, 103, 107],
        [ 86, 105, 109],
        [ 74,  95,  98]],

       [[ 69,  89, 100],
        [ 60,  80,  91],
        [ 53,  73,  84],
        ...,
        [ 74,  92,  96],
        [ 76,  95,  99],
        [ 71,  90,  94]],

       [[ 56,  78,  89],
        [ 55,  77,  88],
        [ 57,  80,  88],
        ...,
        [ 80,  98, 102],
        [ 83, 102, 106],
        [ 86, 105, 109]],

       ...,

       [[ 43,  32,  46],
        [ 41,  30,  44],
        [ 46,  35,  49],
        ...,
        [191, 187, 204],
        [192, 188, 205],
        [194, 190, 207]],

       [[ 41,  29,  43],
        [ 38,  26,  40],
        [ 45,  33,  47],
        ...,
        [184, 180, 197],
        [184, 180, 197],
        [187, 183, 200]],

       [[ 42,  28,  43],
        [ 39,  25,  40],
        [ 46,  32,  47],
        ...,
        [175, 171, 188],
        [171, 167, 184],
        [174, 171, 188]]

In [138]:
Kroos.size, Kroos.shape

(3506400, (1200, 974, 3))

In [141]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 1.53502913,  0.56644004,  0.14926509, -1.078278  ,  1.39547227],
       [ 1.78748405, -0.56951726,  0.17538653, -0.46250554, -1.0858006 ],
       [ 0.63973599, -0.38586334, -0.77576235,  0.99571135, -1.93320478]])

In [142]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])